### ISSUE TITLE
Only installable code should be in lib/

### ISSUE THREAD

**Issue by ugexe** [css-raku/CSS-Specification-raku#4]
Note how the second command does not work on this repo:
`CSS-Specification-p6.git$ prove -v -e 'perl6 -Ilib' t/`
`CSS-Specification-p6.git$ prove -v -e 'perl6 -I.' t/`

**Comment by dwarring** [comment]
Have moved non-installables from lib. I've go in the habit of testing with -I. more often.
Thanks!
